modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "keymod"
version = "1.0"
displayName = "Keychains: Supplementaries"
authors = "Eyae"
description = '''A simple mod to add keychains to store and use Supplementaries keys'''
credits="Ebridger [Keychain Sprite]"

[[mixins]]
config = "keymod.mixins.json"

[[dependencies."keymod"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."keymod"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies."keymod"]]
modId = "supplementaries"
type = "required"
versionRange = "[1.21-3.4.20,)"
ordering = "NONE"
side = "BOTH"

